- hosts: all:!localhost
  become: True
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        state: latest
        update_cache: yes

    - name: Install unattended-upgrades on Debian/Ubuntu
      package:
        name: unattended-upgrades
        state: present
      when: ansible_os_family == "Debian"

    - name: Enable unattended-upgrades service
      command: dpkg-reconfigure -f noninteractive unattended-upgrades
      when: ansible_os_family == "Debian"
        
    - name: Ensure tzdata is installed
      apt:
        name: tzdata
        state: present
        update_cache: true

    - name: Set timezone to Jakarta
      timezone:
        name: Asia/Jakarta
    
    - name: Install packages
      apt:
        name:
          - git
        update_cache: true
