- hosts: all:!localhost
  become: true
  tasks:
    - name: Ensure required packages for apt key management are installed
      apt:
        name:
          - gnupg
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: yes

- hosts: all:!localhost
  become: true
  roles:
    - role: geerlingguy.pip
      pip_executable: pip3
      vars:
        pip_install_packages:
          - name: jsondiff
          - name: pyyaml
          - name: docker

    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose: false

